### ISSUE TITLE
Problem running ./index setup on macos

### ISSUE THREAD

**Issue by therealdano** [asamuzaK/withExEditorHost#59] opened 2019-03-31 06:31 UTC
When running ./index setup on MacOS 10.14 using the macos.zip packages form v5.0.5 and v5.0.6, I get the same error:

```$ ./index setup
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module './modules/common'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/dano/withExEditorHost/index.js:6:28)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)```

Version v5.0.2 doesn't have this problem.

**Comment by asamuzaK** [comment] 2019-03-31 07:55
Can you try [Release v5.0.7-a.1 · asamuzaK/withExEditorHost](https://github.com/asamuzaK/withExEditorHost/releases/tag/v5.0.7-a.1)

**Comment by JontAlle** [comment] 2019-03-31 16:31
I also had this error but with 5.0.7-a1 the issue is resolved.
However I still get the much more serious error, when I try to use the editor. 
Trying to edit a webpage text gives an error that "there are no input and output streams." I dont have the exact message because it only appears for a sec.  Fedora has an 
error message handler, where you click on the top screen and it gives the errors. However this error
fails to appear in that message handler board.

I then ran the following debugger for node:
node /usr/local/src/withExEditorHost-5.0.2/index.js > /tmp/index.log 2>&1
Here is the only output even after I tried (without success) to edit a blog page, whic always worked prior to 5.0.5:
cat index.log 
(node:5090) ExperimentalWarning: The fs.promises API is experimental
C{"withexeditorhost":{"message":"getEditorConfig","status":"ready"}}jba@x1ear:/tmp$ rm index.log 
jba@x1ear:/tmp$ node /usr/local/src/withExEditorHost-5.0.2/index.js > /tmp/index.log 2>&1

Thus the error when using wihtexeditor does not appear in the node log file. In the past I did see
errors, but no more. So I feel that what I'm doing is correct. It does note logging on index.js.

One last very minor point: To run the install  one must chmod +x index.js. In the past this was not stated in the web page. I just checked again, at:
https://github.com/asamuzaK/withExEditorHost/blob/v5.0.7-a.1/README.md
and the chmod +x index is not mentioned.  It may be a small point, but for the novice linux user, it could be  a "show-stopper."

**Comment by asamuzaK** [comment] 2019-03-31 23:59
@JontAlle 
This is an issue about the binary of the host.
Your issue is already tracked in [error starting with 5.0.6 · Issue #110 · asamuzaK/withExEditor](https://github.com/asamuzaK/withExEditor/issues/110) and I have advised you to get the host from npm.
Please do not write around everywhere.

PS:
JavaScript files should not have x permission.

**Comment by asamuzaK** [comment] 2019-04-05 01:05
@therealdano 
Still in trouble with latest binary?

**Comment by JontAlle** [comment] 2019-04-05 11:10
It is not working, and I have temporally given up, after many hrs of working on this. I'm back to editing the old way, which is bad. I will try again with later binarys in the next week. Right now I dont have time  for it.

**Comment by asamuzaK** [comment] 2019-04-29 07:08
There is no reply, so I will close the issue.

**Closed by asamuzaK** 2019-04-29 07:08 UTC
Labels: need info
