### ISSUE TITLE
v5.2.1 and v5.1.8 index does not work on CentOS 7

### ISSUE THREAD

**Issue by therealdano** [asamuzaK/withExEditorHost#68] opened 2019-10-30 00:44 UTC
It looks like the development system has a higher libstdc++ than CentOS 7. When I try to run index, I get:
<pre><code>$ ./index setup
./index: /lib64/libstdc++.so.6: version 'GLIBCXX_3.4.20 not found (required by ./index)
./index: /lib64/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found (required by ./index)
./index: /lib64/libstdc++.so.6: version 'CXXABI_1.3.9' not found (required by ./index)
</code></pre>
I am running libstdc++-4.8.5-39.el7.x86_64, which only has GLIBCXX_3.4.19 and CXXABI_1.3.7. Would it be possible to continue to support that version combination for a while? CentOS 7 will still get full updates until Q4 of 2020.

**Comment by asamuzaK** [comment] 2019-10-30 07:32
The binaries are built using a module called [nexe](https://github.com/nexe/nexe).
Therefore, I do not know in detail how nexe creates their binaries for each OS.
If you need such support, please contact the developer of nexe.

As a workaround, install Node.js and get withExEditorHost from npm.
For details, refer to [Host setup from npm](https://github.com/asamuzaK/withExEditorHost#host-setup-from-npm)

**Comment by asamuzaK** [comment] 2019-10-31 00:10
Ref [How To Install Nodejs on CentOS/RHEL 7/6 - TecAdmin](https://tecadmin.net/install-latest-nodejs-and-npm-on-centos/)

**Comment by therealdano** [comment] 2019-10-31 01:54
Thanks, the nodejs and host setup from npm instructions both worked.

As for the libstdc++ issue, I suppose I can attempt to create a binary with nexe on a CentOS 7 system and see what happens. When you create the binaries, do you use a Debian or Ubuntu host?

**Comment by asamuzaK** [comment] 2019-10-31 02:42
I create 32bit binaries (both Windows and Linux) on my local Windows PC.
Other 64bit binaries (Windows, Mac, Linux) are created automatically by travis.

Binaries are for the people who find it difficult to install Node.js.
You already have Node.js installed, so you don't need to use binary anymore.

For a note, it seems that this issue is caused by V8 engine which Node.js uses.
See [Node.js 12 - V8 version roadmap · Issue #25082 · nodejs/node](https://github.com/nodejs/node/issues/25082)

**Comment by asamuzaK** [comment] 2019-11-01 16:45
I'll close this.

**Closed by asamuzaK** 2019-11-01 16:45 UTC
Labels: wontfix
